package com.axallant.rentcloud.maintenance;

public enum MaintenanceErrorCode {

	INVALID_USER,
	USER_NOT_FOUND,
	SERVICE_REQUEST_NOT_FOUND,
	UNAUTHORIZED,
	INVALID_TENANT,
	INVALID_LANDLORD,
	ATTRIBUTE_MISSING, 
	ELEMENT_NOT_EXIST,
	RESTTEMPLATE_CLIENT_ERROR, 
	AWS_S3_FILE_ERROR, 
	FILE_IO_ERROR
	
}
